//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.StringResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.StringResource.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال موفق با API.
        /// </summary>
        public static string API_OK {
            get {
                return ResourceManager.GetString("API_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم ارسال.
        /// </summary>
        public static string Fault {
            get {
                return ResourceManager.GetString("Fault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانم.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال فقط با GSM.
        /// </summary>
        public static string ForceGSM {
            get {
                return ResourceManager.GetString("ForceGSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال موفق با GSM.
        /// </summary>
        public static string GSM_OK {
            get {
                return ResourceManager.GetString("GSM_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهم.
        /// </summary>
        public static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آقا.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در حراکثر کاراکتر ورودی.
        /// </summary>
        public static string MaxErrorMessage {
            get {
                return ResourceManager.GetString("MaxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیامک جدید.
        /// </summary>
        public static string NEWSMS {
            get {
                return ResourceManager.GetString("NEWSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معمولی.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن این بخش الزامی است.
        /// </summary>
        public static string RequiredErrorMessage {
            get {
                return ResourceManager.GetString("RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال مجدد.
        /// </summary>
        public static string SendAgain {
            get {
                return ResourceManager.GetString("SendAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال با GSM.
        /// </summary>
        public static string SendGSM {
            get {
                return ResourceManager.GetString("SendGSM", resourceCulture);
            }
        }
    }
}
