// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811222746_test13")]
    partial class test13
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Basic.Facilities.InsertDataLog", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ContRecord")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTimeInsert")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descpription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<long>("ViewListID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ViewListID");

                    b.ToTable("InsertDataLog", "Service");
                });

            modelBuilder.Entity("Entities.Basic.Facilities.ViewList", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ViewName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("SchemaName", "ViewName")
                        .IsUnique()
                        .HasDatabaseName("UK_ViweList_View");

                    b.ToTable("ViewList", "Service");
                });

            modelBuilder.Entity("Entities.Basic.Personel.Gender", b =>
                {
                    b.Property<byte>("ID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("UK_Gender_Title");

                    b.ToTable("Gender", "HR");

                    b.HasData(
                        new
                        {
                            ID = (byte)1,
                            Title = "خانم"
                        },
                        new
                        {
                            ID = (byte)2,
                            Title = "آقا"
                        });
                });

            modelBuilder.Entity("Entities.Basic.Personel.Group", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("UK_Group_Title");

                    b.ToTable("Group", "HR");
                });

            modelBuilder.Entity("Entities.Basic.Personel.Person", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte>("GenderID")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PersonCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.HasIndex("GenderID");

                    b.HasIndex("PersonCode")
                        .IsUnique()
                        .HasDatabaseName("UK_Person_PersonCode");

                    b.ToTable("Person", "HR");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            FirstName = "ناشتاس",
                            GenderID = (byte)2,
                            IsActive = true,
                            LastName = "ناشناس",
                            PersonCode = "0"
                        },
                        new
                        {
                            ID = 2L,
                            FirstName = "admin",
                            GenderID = (byte)2,
                            IsActive = true,
                            LastName = "admin",
                            PersonCode = "1"
                        });
                });

            modelBuilder.Entity("Entities.Basic.Personel.PersonGroup", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("GroupID")
                        .HasColumnType("bigint");

                    b.Property<long>("PersonID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("GroupID");

                    b.HasIndex("PersonID", "GroupID")
                        .IsUnique();

                    b.ToTable("PersonGroup", "HR");
                });

            modelBuilder.Entity("Entities.Basic.Personel.PersonPost", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("PersonID")
                        .HasColumnType("bigint");

                    b.Property<long>("PostID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("PostID");

                    b.HasIndex("PersonID", "PostID")
                        .IsUnique();

                    b.ToTable("PersonPost", "HR");
                });

            modelBuilder.Entity("Entities.Basic.Personel.PersonUnit", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("PersonID")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("UnitID");

                    b.HasIndex("PersonID", "UnitID")
                        .IsUnique();

                    b.ToTable("PersonUnit", "HR");
                });

            modelBuilder.Entity("Entities.Basic.Personel.PhonNumbers", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nummber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("PersonID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("PersonID");

                    b.ToTable("PhonNumbers", "HR");
                });

            modelBuilder.Entity("Entities.Basic.Personel.Post", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("CodeGroup")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("UK_Post_Title");

                    b.ToTable("Post", "HR");
                });

            modelBuilder.Entity("Entities.Basic.Personel.Unit", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("ParentUnitID")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UK_Unit_Code");

                    b.HasIndex("ParentUnitID");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("UK_Unit_Title");

                    b.ToTable("Unit", "HR");
                });

            modelBuilder.Entity("Entities.Basic.SMS.MessageLog", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActionDateTime")
                        .HasColumnType("DateTime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<long>("MessageSendID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProviderMessageID")
                        .HasColumnType("bigint");

                    b.Property<bool>("SendActive")
                        .HasColumnType("bit");

                    b.Property<byte>("SendStatusID")
                        .HasColumnType("tinyint");

                    b.Property<string>("StatusCodeReturn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MessageSendID");

                    b.HasIndex("SendStatusID");

                    b.ToTable("MessageLog", "SMS");
                });

            modelBuilder.Entity("Entities.Basic.SMS.MessageSend", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateTimeSend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("InsertDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("MaximumTrySendSMS")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PhoneNumberID")
                        .HasColumnType("bigint");

                    b.Property<byte>("SendImportanceID")
                        .HasColumnType("tinyint");

                    b.Property<int?>("SmsProviderID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PhoneNumberID");

                    b.HasIndex("SendImportanceID");

                    b.HasIndex("SmsProviderID");

                    b.HasIndex("UserID");

                    b.ToTable("MessageSend", "SMS");
                });

            modelBuilder.Entity("Entities.Basic.SMS.SMSProvider", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("APIKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomainName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MethodSendUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhonSender")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PhonSender")
                        .IsUnique()
                        .HasDatabaseName("UK_SmsProvider_PhonSender")
                        .HasFilter("[PhonSender] IS NOT NULL");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("UK_SmsProvidor_Title");

                    b.ToTable("SMSProvider", "SMS");
                });

            modelBuilder.Entity("Entities.Basic.SMS.SendImportance", b =>
                {
                    b.Property<byte>("ID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("UK_Gender_Title");

                    b.ToTable("SendImportance", "SMS");

                    b.HasData(
                        new
                        {
                            ID = (byte)1,
                            Title = "مهم"
                        },
                        new
                        {
                            ID = (byte)2,
                            Title = "معمولی"
                        });
                });

            modelBuilder.Entity("Entities.Basic.SMS.SendStatus", b =>
                {
                    b.Property<byte>("ID")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("UK_SendStatus_Title");

                    b.ToTable("SendStatus", "SMS");

                    b.HasData(
                        new
                        {
                            ID = (byte)1,
                            Title = "پیامک جدید"
                        },
                        new
                        {
                            ID = (byte)2,
                            Title = "ارسال مجدد"
                        },
                        new
                        {
                            ID = (byte)3,
                            Title = "ارسال موفق با API"
                        },
                        new
                        {
                            ID = (byte)4,
                            Title = "عدم ارسال"
                        });
                });

            modelBuilder.Entity("Entities.Basic.Security.AccesseGroup", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("GroupID")
                        .HasColumnType("bigint");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GroupID");

                    b.HasIndex("UserID", "GroupID")
                        .IsUnique();

                    b.ToTable("AccesseGroup", "Security");
                });

            modelBuilder.Entity("Entities.Basic.Security.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PersonID")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("ApplicationUser", "Security");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC-ADMIN-CONCURRENCY-STAMP",
                            Email = "admin@mammut.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MAMMUT.LOCAL",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAELDettaU5Kme+ZbVgKULFy6VVECc5TmQiKN+ATbVW1fivNXUQV3j+dsAmfdwJYFYWA==",
                            PersonID = 2L,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC-ADMIN-SECURITY-STAMP",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC-USER-CONCURRENCY-STAMP",
                            Email = "user@mammut.local",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@MAMMUT.LOCAL",
                            NormalizedUserName = "user",
                            PasswordHash = "AQAAAAEAACcQAAAAENEWUXADh8n9F9Mct8P19Owit+eqqTkHHWe5oUjpBod9eczN7FuXTqVPikhcE7TXWQ==",
                            PersonID = 1L,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC-USER-SECURITY-STAMP",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("Entities.Basic.ViewModel.ViewModelMessage", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AddAnonymous")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateInsert")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimeSend")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasError")
                        .HasColumnType("bit");

                    b.Property<bool>("Importance")
                        .HasColumnType("bit");

                    b.Property<bool>("IsComlpete")
                        .HasColumnType("bit");

                    b.Property<int>("MaximumTrySendSMS")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MessageSendID")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmsProviderTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ViewModelMessages");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "ADMIN-ROLE-CONCURRENCY-STAMP",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "USERS-ROLE-CONCURRENCY-STAMP",
                            Name = "Users",
                            NormalizedName = "USERS"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Entities.Basic.Facilities.InsertDataLog", b =>
                {
                    b.HasOne("Entities.Basic.Facilities.ViewList", "InsertDataLog_ViewList")
                        .WithMany("ViewList_InsertDataLog")
                        .HasForeignKey("ViewListID")
                        .HasConstraintName("FK_ViewList_InsertDataLog_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsertDataLog_ViewList");
                });

            modelBuilder.Entity("Entities.Basic.Personel.Person", b =>
                {
                    b.HasOne("Entities.Basic.Personel.Gender", "Personnel_Gender")
                        .WithMany("Gender_Personnel")
                        .HasForeignKey("GenderID")
                        .HasConstraintName("FK_Person_Gender_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel_Gender");
                });

            modelBuilder.Entity("Entities.Basic.Personel.PersonGroup", b =>
                {
                    b.HasOne("Entities.Basic.Personel.Group", "PersonGroup_Group")
                        .WithMany("Group_PersonGroup")
                        .HasForeignKey("GroupID")
                        .HasConstraintName("FK_PersonGroup_Group_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Basic.Personel.Person", "PersonGroup_Person")
                        .WithMany("Person_PersonGroup")
                        .HasForeignKey("PersonID")
                        .HasConstraintName("FK_PersonGroup_Person_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonGroup_Group");

                    b.Navigation("PersonGroup_Person");
                });

            modelBuilder.Entity("Entities.Basic.Personel.PersonPost", b =>
                {
                    b.HasOne("Entities.Basic.Personel.Person", "PesonPost_Person")
                        .WithMany("Person_PersonPost")
                        .HasForeignKey("PersonID")
                        .HasConstraintName("FK_PersonPost_Person_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Basic.Personel.Post", "PesonPost_Post")
                        .WithMany("Post_PersonPost")
                        .HasForeignKey("PostID")
                        .HasConstraintName("FK_PersonPost_Post_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PesonPost_Person");

                    b.Navigation("PesonPost_Post");
                });

            modelBuilder.Entity("Entities.Basic.Personel.PersonUnit", b =>
                {
                    b.HasOne("Entities.Basic.Personel.Person", "PersonUnit_Person")
                        .WithMany("Person_PersonUnit")
                        .HasForeignKey("PersonID")
                        .HasConstraintName("FK_PersonUnit_Person_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Basic.Personel.Unit", "PersonUnit_Unit")
                        .WithMany("Unit_PersonUnit")
                        .HasForeignKey("UnitID")
                        .HasConstraintName("FK_PersonUnit_Unit_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonUnit_Person");

                    b.Navigation("PersonUnit_Unit");
                });

            modelBuilder.Entity("Entities.Basic.Personel.PhonNumbers", b =>
                {
                    b.HasOne("Entities.Basic.Personel.Person", "Phone_Person")
                        .WithMany("Person_PhoneNumbers")
                        .HasForeignKey("PersonID")
                        .HasConstraintName("FK_PhoneNumber_Person_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phone_Person");
                });

            modelBuilder.Entity("Entities.Basic.Personel.Unit", b =>
                {
                    b.HasOne("Entities.Basic.Personel.Unit", "ParentUnit")
                        .WithMany("ChildUnit")
                        .HasForeignKey("ParentUnitID");

                    b.Navigation("ParentUnit");
                });

            modelBuilder.Entity("Entities.Basic.SMS.MessageLog", b =>
                {
                    b.HasOne("Entities.Basic.SMS.MessageSend", "MessageLog_MessageSend")
                        .WithMany("MessageSend_MessageLog")
                        .HasForeignKey("MessageSendID")
                        .HasConstraintName("FK_MessageLog_MessageSend_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Basic.SMS.SendStatus", "MessageLog_SendStatus")
                        .WithMany("SendStatus_MessageLog")
                        .HasForeignKey("SendStatusID")
                        .HasConstraintName("FK_MessageLog_SendStatus_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageLog_MessageSend");

                    b.Navigation("MessageLog_SendStatus");
                });

            modelBuilder.Entity("Entities.Basic.SMS.MessageSend", b =>
                {
                    b.HasOne("Entities.Basic.Personel.PhonNumbers", "PhoneNummber")
                        .WithMany("MessageSend_PhoneNumer")
                        .HasForeignKey("PhoneNumberID")
                        .HasConstraintName("FK_MessageSend_PhoneNumber_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Basic.SMS.SendImportance", "MessageSend_SendImportance")
                        .WithMany("SendImportance_MessageSend")
                        .HasForeignKey("SendImportanceID")
                        .HasConstraintName("FK_MessageSend_SendImportance_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Basic.SMS.SMSProvider", "MessageSend_SmsProvider")
                        .WithMany("SmsProvider_MessageSend")
                        .HasForeignKey("SmsProviderID")
                        .HasConstraintName("FK_MessageSend_SMSProvider_ID");

                    b.HasOne("Entities.Basic.Security.ApplicationUser", "MessageSend_User")
                        .WithMany("ApplicationUser_MessageSend")
                        .HasForeignKey("UserID")
                        .HasConstraintName("FK_MessageSend_ApplicationUser_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MessageSend_SendImportance");

                    b.Navigation("MessageSend_SmsProvider");

                    b.Navigation("MessageSend_User");

                    b.Navigation("PhoneNummber");
                });

            modelBuilder.Entity("Entities.Basic.Security.AccesseGroup", b =>
                {
                    b.HasOne("Entities.Basic.Personel.Group", "AccesseGroup_Group")
                        .WithMany("Group_AccesseGroup")
                        .HasForeignKey("GroupID")
                        .HasConstraintName("FK_AccesseGroup_Group_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Basic.Security.ApplicationUser", "AccesseGroup_ApplicationUser")
                        .WithMany("ApplicationUser_AccesseGroup")
                        .HasForeignKey("UserID")
                        .HasConstraintName("FK_AccesseGroup_User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccesseGroup_ApplicationUser");

                    b.Navigation("AccesseGroup_Group");
                });

            modelBuilder.Entity("Entities.Basic.Security.ApplicationUser", b =>
                {
                    b.HasOne("Entities.Basic.Personel.Person", "Person")
                        .WithOne()
                        .HasForeignKey("Entities.Basic.Security.ApplicationUser", "PersonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Entities.Basic.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Entities.Basic.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Basic.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Entities.Basic.Security.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Basic.Facilities.ViewList", b =>
                {
                    b.Navigation("ViewList_InsertDataLog");
                });

            modelBuilder.Entity("Entities.Basic.Personel.Gender", b =>
                {
                    b.Navigation("Gender_Personnel");
                });

            modelBuilder.Entity("Entities.Basic.Personel.Group", b =>
                {
                    b.Navigation("Group_AccesseGroup");

                    b.Navigation("Group_PersonGroup");
                });

            modelBuilder.Entity("Entities.Basic.Personel.Person", b =>
                {
                    b.Navigation("Person_PersonGroup");

                    b.Navigation("Person_PersonPost");

                    b.Navigation("Person_PersonUnit");

                    b.Navigation("Person_PhoneNumbers");
                });

            modelBuilder.Entity("Entities.Basic.Personel.PhonNumbers", b =>
                {
                    b.Navigation("MessageSend_PhoneNumer");
                });

            modelBuilder.Entity("Entities.Basic.Personel.Post", b =>
                {
                    b.Navigation("Post_PersonPost");
                });

            modelBuilder.Entity("Entities.Basic.Personel.Unit", b =>
                {
                    b.Navigation("ChildUnit");

                    b.Navigation("Unit_PersonUnit");
                });

            modelBuilder.Entity("Entities.Basic.SMS.MessageSend", b =>
                {
                    b.Navigation("MessageSend_MessageLog");
                });

            modelBuilder.Entity("Entities.Basic.SMS.SMSProvider", b =>
                {
                    b.Navigation("SmsProvider_MessageSend");
                });

            modelBuilder.Entity("Entities.Basic.SMS.SendImportance", b =>
                {
                    b.Navigation("SendImportance_MessageSend");
                });

            modelBuilder.Entity("Entities.Basic.SMS.SendStatus", b =>
                {
                    b.Navigation("SendStatus_MessageLog");
                });

            modelBuilder.Entity("Entities.Basic.Security.ApplicationUser", b =>
                {
                    b.Navigation("ApplicationUser_AccesseGroup");

                    b.Navigation("ApplicationUser_MessageSend");
                });
#pragma warning restore 612, 618
        }
    }
}
